WorkflowGrammar :
    WorkflowDoc <- WorkflowHeader WorkflowDefinition*

    WorkflowHeader <- "options" "{" WorkflowOption* "}"

    WorkflowOption <- identifier ("." identifier)? = .* ";"

    WorkflowDefinition <- "workflow" identifier "{" WorkflowHeader? WorkflowElement* "}"

    WorkflowElement <- identifier ("." identifier)? "{" WorkflowSetting* "}"

    WorkflowSetting <- WorkflowOption | WorkflowElement
