/**
Generated by dxx-tool {{dxx.version}}
Timestamp {{dxx.timeStamp}}
**/
module {{app.packageName}}.app;

private import aermicioi.aedi;

private import dxx.util;
private import dxx.app;

private import {{app.packageName}}.plugin;

import dxx.sys.loader;

version(unittest) {
} else {
  mixin pluginMain;
}

mixin registerPlugin!{{app.pluginClassName}};
